### PR TITLE
Changes to feature/multiple platforms

### PR DESCRIPTION
**Pull request by tmspzz**
- Updated with master
- Removed unused language extensions
- Removed some dependencies
- Made `TargetPlatform` instance of Read and Show (think CustomStringConvertible and StringLiteralConvertible in Swift)
- `rome list --missing|present [<platform>, <platfrom> ...]` removed --platform Option as it was awkward to either specify `--platform iOS --platform watchO`S or `--platform ios,watchos` with no spaces

I'm also open to keep --platform as you have implemented it. What do you think?

Suggestion: Most of the minor changes (like removing parenthesis and so on) were suggested to me by `hlint`. I suppose you don't have it installed.

### CODE REVIEW

**Comment by r-peck** [comment]
- Thanks for the suggestion about hlint. I'm new to Haskell and had not come across it yet.
- As far as `Show` and `Read`:
    - I originally started to make `TargetPlatform` an instance of `Read`, but got derailed for some reason I can no longer remember.
    - `Show` I originally wanted to have reflect the constructors as they were in code while having `targetPlatformName` reflect each platform with casing to match cache layout and Carthage docs, but looking at it after the fact that's probably unnecessary.
    - Definitely think your changes make more sense.
- For the platforms option, I think it should stay as `--platform` for a few reasons:
    - It is consistent with Carthage. It also lacks support for spaces. `carthage build --platform watchos ios` will only build watchOS (`ios` gets treated as a framework argument), but `carthage build --platform watchos,ios` works as expected. You can also wrap in quotes if you want spaces: `--platform 'watchos, ios'`.
    - For upload / download commands, there's no differentiation between framework arguments and platform arguments. Running `rome upload watchos FrameworkA` or `rome upload FrameworkA watchos` will still run for all platforms since `watchos` is treated like a framework argument.
- Do you have a history preference as far as rebasing to maintain linear history? It looks like there's a merge commit in your branch. We could rebase my branch from your master and re-apply your changes to that instead.

**Comment by tmspzz** [comment]
Ok let's keep `--platform` as is in your implementation

I don't have preferences about the history. We can rebase your branch to my master but I'm not sure about how well this will play when applying my changes. What do we do with this pull request? I guess you just close it? Should I open another branch on my repo to direct your pull request there?

I have changed also a helper function in the part the parses the platforms. I think it still behaves the same but maybe we want to keep an eye on that one.

Also there a couple of pure functions that are good candidates for tests. I think it could be a nice exercise but they can come at a later time.

**Comment by r-peck** [comment]
I can close this PR, debase my branch from your master, then cherry-pick your changes. The PR to your repo can probably stay the same. If you want to review just the re-application of your changes, I can do that on a separate branch and mention you on a PR to the feature branch. I'm traveling today, so likely will be unable to make progress on this until tomorrow.

**Comment by tmspzz** [comment]
Sounds good. Let's go ahead with that. Safe traveling.

**Comment by r-peck** [comment]
Closing - will reopen with the changes applied to a rebased branch.

**Pull request closed without merging**
